[2024-12-05 21:13:58,283] 22 root - INFO - Data Ingestion has been started
[2024-12-05 21:13:58,283] 24 root - INFO - Data reading using Pandas from local file system
[2024-12-05 21:13:58,307] 26 root - INFO - Data Reading has been completed
[2024-12-05 21:13:58,353] 30 root - INFO - Raw data has been stored
[2024-12-05 21:13:58,357] 33 root - INFO - Raw data has been splitted into Train and Test set
[2024-12-05 21:13:58,412] 38 root - INFO - Data Ingestion has been completed!
[2024-12-05 21:13:58,413] 49 root - INFO - Created feature store configuration at /home/lutful/telco-customer-churn-ml-project/feature_repo/feature_store.yaml
[2024-12-05 21:13:58,413] 53 root - INFO - Configuration file content:
project: Churn_Prediction
provider: local
registry: data/registry.db
online_store:
  type: sqlite
offline_store:
  type: file
entity_key_serialization_version: 2
[2024-12-05 21:13:58,894] 230 feast.infra.registry.registry - INFO - Registry file not found. Creating new registry.
[2024-12-05 21:13:58,900] 57 root - INFO - Feature store initialized successfully
[2024-12-05 21:13:58,925] 112 root - INFO - Read train and test data completed
[2024-12-05 21:13:58,925] 116 root - INFO - target Column Churn
[2024-12-05 21:13:58,926] 121 root - INFO - Numerical Columns ['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']
[2024-12-05 21:13:58,926] 125 root - INFO - Categorical Columns ['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']
[2024-12-05 21:13:58,926] 127 root - INFO - Obtaining preprocessing object
[2024-12-05 21:13:58,926] 65 root - INFO - Data Transformation Started
[2024-12-05 21:13:58,929] 136 root - INFO - Applying preprocessing object on training and testing datasets.
[2024-12-05 21:13:58,990] 141 root - INFO - Starting feature store operations
[2024-12-05 21:13:59,051] 186 root - INFO - Saved feature data to feature_repo/data/train_features.parquet
[2024-12-05 21:13:59,054] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[2024-12-05 21:13:59,054] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[2024-12-05 21:13:59,056] 409 root - WARNING - Cannot use sqlite_vec for vector search
[2024-12-05 21:13:59,079] 231 root - INFO - Applied entity and feature view for train
[2024-12-05 21:13:59,079] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[2024-12-05 21:13:59,083] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[2024-12-05 21:13:59,084] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[2024-12-05 21:14:03,645] 238 root - INFO - Materialized features successfully
[2024-12-05 21:14:03,646] 145 root - INFO - Pushed training data to feature store
[2024-12-05 21:14:03,653] 186 root - INFO - Saved feature data to feature_repo/data/test_features.parquet
[2024-12-05 21:14:03,656] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[2024-12-05 21:14:03,674] 231 root - INFO - Applied entity and feature view for test
[2024-12-05 21:14:03,674] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[2024-12-05 21:14:03,678] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[2024-12-05 21:14:03,678] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[2024-12-05 21:14:07,223] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[2024-12-05 21:14:08,351] 238 root - INFO - Materialized features successfully
[2024-12-05 21:14:08,351] 148 root - INFO - Pushed testing data to feature store
[2024-12-05 21:14:08,869] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fec3a143c20>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Modular_Workflow_Prediction_Pipeline
[2024-12-05 21:14:13,713] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fec3a143dd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Modular_Workflow_Prediction_Pipeline
[2024-12-05 21:14:22,450] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fec3a143f50>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Modular_Workflow_Prediction_Pipeline
[2024-12-05 21:14:39,054] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fec3a178110>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Modular_Workflow_Prediction_Pipeline
[2024-12-05 21:15:11,825] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fec3a178290>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Modular_Workflow_Prediction_Pipeline
